title: Mohamed Learns Cybersecurity
description: Here, I will blog learning experiences and projects in my cybersecurity career.
theme: jekyll-theme-midnight
show_downloads: false
author:
  name: Mohamed Ashfaq Shajahan
  email: contact.m.a.shajahan@gmail.com
exclude:
  - README.md
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about/
  
  
  
  
